service: ringcentral-google-forms-notification-app
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  environment: ${file(./env.yml)}
  profile: default
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: ""
  deploymentBucket:
    tags:
      Department: dev
      Owner: Your name
      Stage: production
      Environment: your-env-tag
      Team: your-team
      Name: ringcentral-google-forms-notification-app
  tags:
    Department: dev
    Owner: Your name
    Stage: production
    Environment: your-env-tag
    Team: your-team
    Name: ringcentral-google-forms-notification-app
package:
  excludeDevDependencies: true
  patterns:
    - '.json'
    - '.js'
    - 'node_modules/**'
functions:
  app:
    handler: lambda.app
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: false
  refresh:
    handler: refreshSubscriptionCron.refresh
    events:
      - schedule: cron(0 4 ? * * *)
      # run refresh daily at 4 AM
resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: google-form-rc-notification-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    subscriptionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: google-form-rc-notification-subscriptions
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
plugins:
  - serverless-deployment-bucket
